<?php 
include('./database.php');

class DataService {
    private $db;
   
    function __construct($name){
        $this->init($name);
    }

    /**
     * A function that sets up the database along with the required tables
     * @var string $name 
     * the name of the database to be created
     */
    private function init($name){
        $this->db = new Database($name);

         $this->db->create_table('Employees', [
            'ID' => 'INT(6) AUTO_INCREMENT PRIMARY KEY',
            'Surname' => 'VARCHAR(50) NOT NULL',
            'Password' => 'VARCHAR(50) NOT NULL'
        ]);

        $this->db->create_table('Machines', [
            'ID' => 'INT(6) AUTO_INCREMENT PRIMARY KEY',
            'Title' => 'VARCHAR(50) NOT NULL'
        ]);

        /**
         * Insert some records to start with
         */
        $this->db->insert_record('employees', ['Surname' => 'Benz', 'Password' => 'Merzedes']);
        $this->db->insert_record('employees', ['Surname' => 'Goethe', 'Password' => 'faust123']);
        $this->db->insert_record('employees', ['Surname' => 'Einstein', 'Password' => 'existence']);
        $this->db->insert_record('employees', ['Surname' => 'Rothschild', 'Password' => 'control']);

        $this->db->insert_record('machines', ['Title' => 'Drill']);
        $this->db->insert_record('machines', ['Title' => 'Hacksaw']);
        $this->db->insert_record('machines', ['Title' => 'Forklift']);
        $this->db->insert_record('machines', ['Title' => 'Crane']);


        $this->db->alter_table('Machines', 'ADD emp_ID INT(6);');
        $this->db->alter_table('Machines', 'ADD FOREIGN KEY (emp_ID) REFERENCES Employee(ID)');
    }

    public function getEmployeeById($id){
        $employee = $this->db->getEmployeeById($id);
        return $employee;
    }

    public function getMachineById($id){
        $machine = $this->db->getMachineById($id);
        return $machine;
    }

    public function getMaxID($table){
        $result = $this->db->getMaxID($table);
        return $result;
    }

    public function getEmployeeIdFromName($name){
        return $this->db->getEmployeeIdFromName($name);
    }

    public function insert_record($table, $obj){
        $obj_to_arr = json_decode(json_encode($obj), true);
        /**
         * properties of the object we do not want to be inserted
         * id because it is autogenerated
         * service because it is only used to connect to database
         * emp_id because when machine is created it is not assigned to anyone, should be NULL
         */
        unset($obj_to_arr['id']);
        unset($obj_to_arr['service']);
        unset($obj_to_arr['emp_id']);
        
        $id = $this->db->insert_record($table, $obj_to_arr);
        return $id;
       
    }

    public function update_record($table, $ops){
        $this->db->update_table($table, $valToUpdate, $id);
    }

    public function getListOfMachinesAndUsage(){
        return $this->db->get_list_of_machines_and_usage();
    }

    public function getAllEmployeeMachines($empID){
       $data = $this->db->getAllEmployeeMachinesByEmployeeID($empID);
       return $data;
    }

    public function getAllEmployees(){
        return $this->db->getAllEmployees();
    }

    public function getAllUnassignedMachines() {
        return $this->db->getAllUnassignedMachines();
    }

    public function assignMachineToEmployee($empID, $machineID){
        $this->db->assignEmployeeToMachine($empID, $machineID);
    }

    public function returnMachine($machineID){
        $this->db->returnMachine($machineID);
    }

}